#!/bin/bash
#
# uninstall-sh
#
# note: this file is not named uninstall.sh to avoid unwanted behavior
# due to implicit rules with "make"
#
# uninstaller for pcap2flow and related files

echo
echo PCAP2FLOW UNINSTALL-SH
echo --------------------
echo

delete_file () {
    if [ -f $1 ]; then
        rm $1
        retval=$?
        if [ $retval != "0" ]; then
            echo "error: could not delete file $1"
        else
            echo "deleted file $1"
        fi
    fi
}

delete_directory () {
    if [ -d $1 ]; then
        rm -rf $1
        retval=$?
        if [ $retval != "0" ]; then
            echo "error: could not delete directory $1"
        else
            echo "deleted directory $1"
        fi
    fi
}

sysname=`uname -s`

if [ "$sysname" == "Darwin" ]; then
    ##
    # Darwin operating system detected
    ##
    echo "System $sysname (Mac OS X) uninstalling ..."

    # Stop the daemon
    launchctl unload /Library/LaunchDaemons/pcap2flow.plist

    # Delete the application files
    delete_file /usr/local/bin/pcap2flow

    delete_file /usr/local/bin/query.py

    delete_directory /usr/local/etc/p2f

    delete_file /Library/LaunchDaemons/pcap2flow.plist

    delete_file /usr/local/share/man/man1/pcap2flow.1

    echo "... done"
    echo
elif [ "$sysname" == "Linux" ]; then
    ##
    # Linux operating system detected
    ##
    echo "System $sysname (Linux) uninstalling ..."

    # Default to sysv for daemon management system
    daemon_system='sysv'
    if [ -f /sbin/init ]; then
        # Check if the file is a symbolic link
        if [ -h /sbin/init ]; then
            # Check whether linked to systemd
            file /sbin/init | grep 'systemd'
            retval=$?
            if [ $retval == "0" ]; then
                daemon_system='systemd'
            fi
        fi
    fi

    # Stop and disable the service
    if [ "$daemon_system" == "sysv" ]; then
        echo "stopping service (this might take some time)"
        service pcap2flow stop
        update-rc.d pcap2flow remove
        service pcap2flow status
    elif [ "$daemon_system" == "systemd" ]; then
        echo "stopping service (this might take some time)"
        systemctl stop pcap2flow.service
        systemctl disable pcap2flow.service
        systemctl status pcap2flow.service
    fi

    # Delete the application files
    delete_file /usr/local/bin/pcap2flow

    delete_file /usr/local/bin/query.py

    delete_directory /usr/local/etc/p2f

    delete_directory /usr/local/share/joy
    delete_directory /usr/local/share/joy/data

    delete_file /usr/local/share/man/man1/pcap2flow.1

    # Delete daemon specific files
    if [ "$daemon_system" == "sysv" ]; then
        delete_file /etc/init.d/pcap2flow

    elif [ "$daemon_system" == "systemd" ]; then
        delete_file /etc/systemd/system/pcap2flow.service
        delete_directory /etc/systemd/system/pcap2flow.service.d
    fi

    echo "... done"
    echo
else
    echo "error: unknown system ($sysname)"
    exit
fi
